export default {
  //Board constants
  CREATE_BOARD: 'CREATE_BOARD',
  BOARD_LIFECYCLE: 'BOARD_LIFECYCLE',

  //Animation constants
  CREATE_INTERVAL: 'CREATE_INTERVAL',
  REMOVE_INTERVAL: 'REMOVE_INTERVAL'
}