export default {
  //Board constants
  CREATE_BOARD: 'CREATE_BOARD',
  BOARD_LIFECYCLE: 'BOARD_LIFECYCLE',
  CELL_CHANGE: 'CELL_CHANGE',
  //Animation constants
  CREATE_INTERVAL: 'CREATE_INTERVAL',
  REMOVE_INTERVAL: 'REMOVE_INTERVAL'
}