export default {
  RANDOM_BOARD: 'RANDOM_BOARD',
  CLEAR_BOARD: 'CLEAR_BOARD',
  DISTRIBUTED_BOARD: 'DISTRIBUTED_BOARD',
  RANDOM_RADIUS_BOARD: 'RANDOM_RADIUS_BOARD',
  MONTE_CARLO: 'MONTE_CARLO',

  //Types of neighbourhood
  VON_NEUMANN: 'VON_NEUMANN',
  MOORE: 'MOORE',
  HEX_LEFT: 'HEX_LEFT',
  HEX_RIGHT: 'HEX_RIGHT',
  HEX_RAND: 'HEX_RAND',
  PENT_RAND: 'PENT_RAND',

  //Types of game
  GAME_OF_LIFE: 'GAME_OF_LIFE',
  GERM_EXPANSION: 'GERM_EXPANSION'
}